language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - develop
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew --no-daemon --stacktrace generateProto test build
after_success:
  - bash <(curl -s https://codecov.io/bash)
